<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="grid.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            Employee<br />
            <br />
            <asp:MultiView ID="MultiView1" runat="server" >
                <asp:View ID="View2" runat="server">
                    view 2<br />
                    <br />
                    <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" CellPadding="4" DataKeyNames="emp_id" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None" Height="50px" Width="125px">
                        <AlternatingRowStyle BackColor="White" />
                        <CommandRowStyle BackColor="#D1DDF1" Font-Bold="True" />
                        <EditRowStyle BackColor="#2461BF" />
                        <FieldHeaderStyle BackColor="#DEE8F5" Font-Bold="True" />
                        <Fields>
                            <asp:BoundField DataField="emp_id" HeaderText="emp_id" ReadOnly="True" SortExpression="emp_id" />
                            <asp:BoundField DataField="emp_name" HeaderText="emp_name" SortExpression="emp_name" />
                            <asp:BoundField DataField="emp_salary" HeaderText="emp_salary" SortExpression="emp_salary" />
                            <asp:BoundField DataField="emp_country" HeaderText="emp_country" SortExpression="emp_country" />
                        </Fields>
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                    </asp:DetailsView>
                    <br />
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Button" />
                </asp:View>
                <asp:View ID="View1" runat="server">
                    Vieew 1<br />
                    <br />
                    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="emp_id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:CommandField ShowSelectButton="True" />
                            <asp:BoundField DataField="emp_id" HeaderText="emp_id" ReadOnly="True" SortExpression="emp_id" />
                            <asp:BoundField DataField="emp_name" HeaderText="emp_name" SortExpression="emp_name" />
                            <asp:BoundField DataField="emp_salary" HeaderText="emp_salary" SortExpression="emp_salary" />
                            <asp:BoundField DataField="emp_country" HeaderText="emp_country" SortExpression="emp_country" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                    <br />
                    <br />
                </asp:View>
            </asp:MultiView>
            <br />
            <br />
            <br />
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [emp] WHERE [emp_id] = @emp_id" InsertCommand="INSERT INTO [emp] ([emp_id], [emp_name], [emp_salary], [emp_country]) VALUES (@emp_id, @emp_name, @emp_salary, @emp_country)" SelectCommand="SELECT * FROM [emp]" UpdateCommand="UPDATE [emp] SET [emp_name] = @emp_name, [emp_salary] = @emp_salary, [emp_country] = @emp_country WHERE [emp_id] = @emp_id">
                <DeleteParameters>
                    <asp:Parameter Name="emp_id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="emp_id" Type="Int32" />
                    <asp:Parameter Name="emp_name" Type="String" />
                    <asp:Parameter Name="emp_salary" Type="Int32" />
                    <asp:Parameter Name="emp_country" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="emp_name" Type="String" />
                    <asp:Parameter Name="emp_salary" Type="Int32" />
                    <asp:Parameter Name="emp_country" Type="String" />
                    <asp:Parameter Name="emp_id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [emp] where emp_id = @emp_id;" DeleteCommand="DELETE FROM [emp] WHERE [emp_id] = @emp_id" InsertCommand="INSERT INTO [emp] ([emp_id], [emp_name], [emp_salary], [emp_country]) VALUES (@emp_id, @emp_name, @emp_salary, @emp_country)" UpdateCommand="UPDATE [emp] SET [emp_name] = @emp_name, [emp_salary] = @emp_salary, [emp_country] = @emp_country WHERE [emp_id] = @emp_id">
                <DeleteParameters>
                    <asp:Parameter Name="emp_id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="emp_id" Type="Int32" />
                    <asp:Parameter Name="emp_name" Type="String" />
                    <asp:Parameter Name="emp_salary" Type="Int32" />
                    <asp:Parameter Name="emp_country" Type="String" />
                </InsertParameters>
                <SelectParameters>
                    <asp:ControlParameter ControlID="GridView1" Name="emp_id" PropertyName="SelectedValue" />
                </SelectParameters>
                <UpdateParameters>
                    <asp:Parameter Name="emp_name" Type="String" />
                    <asp:Parameter Name="emp_salary" Type="Int32" />
                    <asp:Parameter Name="emp_country" Type="String" />
                    <asp:Parameter Name="emp_id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
        </div>
    </form>
</body>
</html>
